package petadoption.api.models;

public enum COLOR_TYPE {
    RED, BLUE, GREEN, YELLOW, ORANGE, PURPLE, PINK, BROWN, BLACK, WHITE, GRAY, CYAN, MAGENTA,
    BEIGE, TEAL, MAROON, NAVY, LIME, CORAL, LAVENDER, GOLD, SILVER, BRONZE, PEACH, MINT,
    TURQUOISE, INDIGO, CREAM, OCHRE, MUSTARD
}
