server:
  port: 8080
  address: 0.0.0.0
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3307/petadoption
    username: root
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    gcp:
      storage:
        credentials:
          location: file:src/main/resources/esoteric-parsec-443418-j9-332ce794dc3f.json
        bucket: sw2-pet-adoption
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

