server:
  port: 8080
  address: 0.0.0.0
spring:
  datasource:
    url: jdbc:mysql://${0.0.0.0:localhost}:3306/petadoption
    username: root
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
