name: Run Unit Tests on PR

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted

    steps:
      # Checkout the code from the PR
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: 'gradle'

      # Cache Gradle dependencies
      - name: Cache Gradle Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Make gradlew executable
        run: chmod +x gradlew

      # Run Unit Tests
      - name: Run Unit Tests
        run: |
          cd pet-adoption-api
          ./gradlew clean test --no-daemon
