name: Run Unit Tests on PR

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted

    steps:
      # Checkout the code from the PR
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK 17 (or any version your project requires)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'gradle'  # Caches Gradle dependencies automatically

      # Cache Gradle dependencies
      - name: Cache Gradle Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      # Run Unit Tests
      - name: Run Unit Tests
        run: ./gradlew clean test --no-daemon
