name: Run Unit Tests on PR

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted

    steps:
      # Checkout code from the PR
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java environment (adjust version if needed)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin' # Use AdoptOpenJDK or Temurin

      # Cache Maven or Gradle dependencies for faster builds
      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Run Maven tests (use Gradle if your project uses it)
      - name: Run Unit Tests
        run: mvn clean test
